version: "3.5"
services:
    db:
        image: "postgres:12"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
networks:
    default:
        name: network-for-test
